server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ridvanozcan91/application-configs
          clone-on-start: true
          skipSslValidation: true